name: Dummy
version: ${version}
main: dev.dummy.DummyPlugin
description: High-version Paper fake player plugin.
api-version: "1.21"
authors:
  - Dummy
permissions:
  dummy.command:
    description: Allows using the base dummy command.
    default: true
  dummy.command.manage-all:
    description: Allows managing dummy players created by other players.
    default: op
  dummy.command.spawn:
    description: Allows spawning dummy players.
    default: true
  dummy.command.remove:
    description: Allows removing dummy players.
    default: true
  dummy.command.delete:
    description: Allows deleting dummy players and their saved data.
    default: true
  dummy.command.list:
    description: Allows listing dummy players.
    default: true
  dummy.command.reload:
    description: Allows reloading Dummy configuration.
    default: op
  dummy.command.config:
    description: Allows changing dummy configuration.
    default: true
  dummy.command.skin:
    description: Allows changing dummy skins.
    default: true
  dummy.command.exp:
    description: Allows transferring dummy experience.
    default: true
  dummy.command.inv:
    description: Allows opening dummy inventories.
    default: true
  dummy.command.tpto:
    description: Allows teleporting to dummy players.
    default: true
  dummy.command.tphere:
    description: Allows teleporting dummy players.
    default: true
  dummy.command.tps:
    description: Allows swapping positions with dummy players.
    default: true
  dummy.command.actions:
    description: Allows controlling dummy actions.
    default: true
